// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/seat/services/seat_svc.proto

package seat_svc // import "simple-restful/exmsgs/seat/services"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import models "simple-restful/exmsgs/seat/models"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Messages
type SeatsRequest struct {
	List        []*models.Seat `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	MinDistance int64          `protobuf:"varint,2,opt,name=min_distance,json=minDistance" json:"min_distance,omitempty"`
	Session     string         `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
	// Confirm booking
	Confirm              bool     `protobuf:"varint,4,opt,name=confirm" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatsRequest) Reset()         { *m = SeatsRequest{} }
func (m *SeatsRequest) String() string { return proto.CompactTextString(m) }
func (*SeatsRequest) ProtoMessage()    {}
func (*SeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{0}
}
func (m *SeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatsRequest.Unmarshal(m, b)
}
func (m *SeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatsRequest.Marshal(b, m, deterministic)
}
func (dst *SeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatsRequest.Merge(dst, src)
}
func (m *SeatsRequest) XXX_Size() int {
	return xxx_messageInfo_SeatsRequest.Size(m)
}
func (m *SeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeatsRequest proto.InternalMessageInfo

func (m *SeatsRequest) GetList() []*models.Seat {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SeatsRequest) GetMinDistance() int64 {
	if m != nil {
		return m.MinDistance
	}
	return 0
}

func (m *SeatsRequest) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *SeatsRequest) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

type GetAvailableSeatsRequest struct {
	CurrentSession       string   `protobuf:"bytes,1,opt,name=current_session,json=currentSession" json:"current_session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvailableSeatsRequest) Reset()         { *m = GetAvailableSeatsRequest{} }
func (m *GetAvailableSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAvailableSeatsRequest) ProtoMessage()    {}
func (*GetAvailableSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{1}
}
func (m *GetAvailableSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvailableSeatsRequest.Unmarshal(m, b)
}
func (m *GetAvailableSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvailableSeatsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAvailableSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvailableSeatsRequest.Merge(dst, src)
}
func (m *GetAvailableSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAvailableSeatsRequest.Size(m)
}
func (m *GetAvailableSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvailableSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvailableSeatsRequest proto.InternalMessageInfo

func (m *GetAvailableSeatsRequest) GetCurrentSession() string {
	if m != nil {
		return m.CurrentSession
	}
	return ""
}

type SetOfSeats struct {
	Row                  int64    `protobuf:"varint,1,opt,name=row" json:"row,omitempty"`
	Cols                 []int64  `protobuf:"varint,2,rep,packed,name=cols" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOfSeats) Reset()         { *m = SetOfSeats{} }
func (m *SetOfSeats) String() string { return proto.CompactTextString(m) }
func (*SetOfSeats) ProtoMessage()    {}
func (*SetOfSeats) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{2}
}
func (m *SetOfSeats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOfSeats.Unmarshal(m, b)
}
func (m *SetOfSeats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOfSeats.Marshal(b, m, deterministic)
}
func (dst *SetOfSeats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOfSeats.Merge(dst, src)
}
func (m *SetOfSeats) XXX_Size() int {
	return xxx_messageInfo_SetOfSeats.Size(m)
}
func (m *SetOfSeats) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOfSeats.DiscardUnknown(m)
}

var xxx_messageInfo_SetOfSeats proto.InternalMessageInfo

func (m *SetOfSeats) GetRow() int64 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *SetOfSeats) GetCols() []int64 {
	if m != nil {
		return m.Cols
	}
	return nil
}

type SeatsResult struct {
	List                 []*SetOfSeats `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	TotalAvailable       int64         `protobuf:"varint,2,opt,name=totalAvailable" json:"totalAvailable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SeatsResult) Reset()         { *m = SeatsResult{} }
func (m *SeatsResult) String() string { return proto.CompactTextString(m) }
func (*SeatsResult) ProtoMessage()    {}
func (*SeatsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{3}
}
func (m *SeatsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatsResult.Unmarshal(m, b)
}
func (m *SeatsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatsResult.Marshal(b, m, deterministic)
}
func (dst *SeatsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatsResult.Merge(dst, src)
}
func (m *SeatsResult) XXX_Size() int {
	return xxx_messageInfo_SeatsResult.Size(m)
}
func (m *SeatsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatsResult.DiscardUnknown(m)
}

var xxx_messageInfo_SeatsResult proto.InternalMessageInfo

func (m *SeatsResult) GetList() []*SetOfSeats {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SeatsResult) GetTotalAvailable() int64 {
	if m != nil {
		return m.TotalAvailable
	}
	return 0
}

type SeatAvailabilityResult struct {
	Available            []*models.Seat `protobuf:"bytes,1,rep,name=available" json:"available,omitempty"`
	Unavailable          []*models.Seat `protobuf:"bytes,2,rep,name=unavailable" json:"unavailable,omitempty"`
	Session              string         `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
	Status               string         `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SeatAvailabilityResult) Reset()         { *m = SeatAvailabilityResult{} }
func (m *SeatAvailabilityResult) String() string { return proto.CompactTextString(m) }
func (*SeatAvailabilityResult) ProtoMessage()    {}
func (*SeatAvailabilityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{4}
}
func (m *SeatAvailabilityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatAvailabilityResult.Unmarshal(m, b)
}
func (m *SeatAvailabilityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatAvailabilityResult.Marshal(b, m, deterministic)
}
func (dst *SeatAvailabilityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatAvailabilityResult.Merge(dst, src)
}
func (m *SeatAvailabilityResult) XXX_Size() int {
	return xxx_messageInfo_SeatAvailabilityResult.Size(m)
}
func (m *SeatAvailabilityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatAvailabilityResult.DiscardUnknown(m)
}

var xxx_messageInfo_SeatAvailabilityResult proto.InternalMessageInfo

func (m *SeatAvailabilityResult) GetAvailable() []*models.Seat {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *SeatAvailabilityResult) GetUnavailable() []*models.Seat {
	if m != nil {
		return m.Unavailable
	}
	return nil
}

func (m *SeatAvailabilityResult) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *SeatAvailabilityResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{5}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type ResultResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultResponse) Reset()         { *m = ResultResponse{} }
func (m *ResultResponse) String() string { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()    {}
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_seat_svc_3f3a13650b5825f3, []int{6}
}
func (m *ResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultResponse.Unmarshal(m, b)
}
func (m *ResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultResponse.Marshal(b, m, deterministic)
}
func (dst *ResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultResponse.Merge(dst, src)
}
func (m *ResultResponse) XXX_Size() int {
	return xxx_messageInfo_ResultResponse.Size(m)
}
func (m *ResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultResponse proto.InternalMessageInfo

func (m *ResultResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*SeatsRequest)(nil), "protos.seat.services.SeatsRequest")
	proto.RegisterType((*GetAvailableSeatsRequest)(nil), "protos.seat.services.GetAvailableSeatsRequest")
	proto.RegisterType((*SetOfSeats)(nil), "protos.seat.services.SetOfSeats")
	proto.RegisterType((*SeatsResult)(nil), "protos.seat.services.SeatsResult")
	proto.RegisterType((*SeatAvailabilityResult)(nil), "protos.seat.services.SeatAvailabilityResult")
	proto.RegisterType((*EmptyRequest)(nil), "protos.seat.services.EmptyRequest")
	proto.RegisterType((*ResultResponse)(nil), "protos.seat.services.ResultResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SeatService service

type SeatServiceClient interface {
	GetAvailableSeats(ctx context.Context, in *GetAvailableSeatsRequest, opts ...grpc.CallOption) (*SeatsResult, error)
	BookSeats(ctx context.Context, in *SeatsRequest, opts ...grpc.CallOption) (*SeatAvailabilityResult, error)
	Reset(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type seatServiceClient struct {
	cc *grpc.ClientConn
}

func NewSeatServiceClient(cc *grpc.ClientConn) SeatServiceClient {
	return &seatServiceClient{cc}
}

func (c *seatServiceClient) GetAvailableSeats(ctx context.Context, in *GetAvailableSeatsRequest, opts ...grpc.CallOption) (*SeatsResult, error) {
	out := new(SeatsResult)
	err := grpc.Invoke(ctx, "/protos.seat.services.SeatService/GetAvailableSeats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) BookSeats(ctx context.Context, in *SeatsRequest, opts ...grpc.CallOption) (*SeatAvailabilityResult, error) {
	out := new(SeatAvailabilityResult)
	err := grpc.Invoke(ctx, "/protos.seat.services.SeatService/BookSeats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) Reset(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/protos.seat.services.SeatService/Reset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SeatService service

type SeatServiceServer interface {
	GetAvailableSeats(context.Context, *GetAvailableSeatsRequest) (*SeatsResult, error)
	BookSeats(context.Context, *SeatsRequest) (*SeatAvailabilityResult, error)
	Reset(context.Context, *EmptyRequest) (*ResultResponse, error)
}

func RegisterSeatServiceServer(s *grpc.Server, srv SeatServiceServer) {
	s.RegisterService(&_SeatService_serviceDesc, srv)
}

func _SeatService_GetAvailableSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).GetAvailableSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.seat.services.SeatService/GetAvailableSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).GetAvailableSeats(ctx, req.(*GetAvailableSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_BookSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).BookSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.seat.services.SeatService/BookSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).BookSeats(ctx, req.(*SeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.seat.services.SeatService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).Reset(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.seat.services.SeatService",
	HandlerType: (*SeatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableSeats",
			Handler:    _SeatService_GetAvailableSeats_Handler,
		},
		{
			MethodName: "BookSeats",
			Handler:    _SeatService_BookSeats_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _SeatService_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/seat/services/seat_svc.proto",
}

func init() {
	proto.RegisterFile("protos/seat/services/seat_svc.proto", fileDescriptor_seat_svc_3f3a13650b5825f3)
}

var fileDescriptor_seat_svc_3f3a13650b5825f3 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x25, 0x4d, 0x5d, 0xed, 0x6d, 0xa9, 0x3a, 0xc8, 0x12, 0x0a, 0x42, 0x36, 0x8a, 0xe6, 0xa1,
	0x4e, 0xa1, 0x8a, 0x0f, 0xfa, 0xe4, 0xaa, 0xf8, 0x28, 0x4e, 0xdf, 0x04, 0x29, 0xb3, 0xd9, 0x5b,
	0x19, 0x76, 0x92, 0xa9, 0xb9, 0x93, 0xaa, 0xdf, 0xe1, 0x47, 0xf8, 0x17, 0x7e, 0x9b, 0x64, 0x26,
	0xd9, 0xa6, 0x6b, 0x5b, 0xdf, 0xee, 0xbd, 0x39, 0xe7, 0xdc, 0xcb, 0x39, 0x61, 0xe0, 0xd1, 0xba,
	0x34, 0xd6, 0xd0, 0x8c, 0x50, 0xda, 0x19, 0x61, 0xb9, 0x51, 0x19, 0xfa, 0x6e, 0x49, 0x9b, 0x8c,
	0xbb, 0xaf, 0xec, 0x81, 0x07, 0xf1, 0x7a, 0xcc, 0x5b, 0xd0, 0xe4, 0x61, 0x97, 0x9a, 0x9b, 0x4b,
	0xd4, 0xbe, 0xf6, 0xa4, 0xe4, 0x57, 0x00, 0xa3, 0x05, 0x4a, 0x4b, 0x02, 0xbf, 0x55, 0x48, 0x96,
	0x4d, 0xa1, 0xaf, 0x15, 0xd9, 0x28, 0x88, 0xc3, 0x74, 0x38, 0x8f, 0x78, 0x57, 0xd4, 0xd3, 0x79,
	0x8d, 0x17, 0x0e, 0xc5, 0xce, 0x60, 0x94, 0xab, 0x62, 0x79, 0xa9, 0xc8, 0xca, 0x22, 0xc3, 0xa8,
	0x17, 0x07, 0x69, 0x28, 0x86, 0xb9, 0x2a, 0xde, 0x35, 0x23, 0x16, 0xc1, 0x6d, 0x42, 0x22, 0x65,
	0x8a, 0x28, 0x8c, 0x83, 0x74, 0x20, 0xda, 0xb6, 0xfe, 0x92, 0x99, 0x62, 0xa5, 0xca, 0x3c, 0xea,
	0xc7, 0x41, 0x7a, 0x47, 0xb4, 0x6d, 0xf2, 0x16, 0xa2, 0x0f, 0x68, 0xdf, 0x6c, 0xa4, 0xd2, 0xf2,
	0x42, 0xe3, 0xce, 0x81, 0x4f, 0xe1, 0x6e, 0x56, 0x95, 0x25, 0x16, 0x76, 0xd9, 0xea, 0x06, 0x4e,
	0x77, 0xdc, 0x8c, 0x17, 0x7e, 0x9a, 0xcc, 0x01, 0x16, 0x68, 0x3f, 0xae, 0x1c, 0x9b, 0xdd, 0x83,
	0xb0, 0x34, 0xdf, 0x1d, 0x34, 0x14, 0x75, 0xc9, 0x18, 0xf4, 0x33, 0xa3, 0x29, 0xea, 0xc5, 0x61,
	0x1a, 0x0a, 0x57, 0x27, 0x57, 0x30, 0x6c, 0x96, 0x51, 0xa5, 0x2d, 0x7b, 0xb1, 0x63, 0x46, 0xcc,
	0xf7, 0x39, 0xcc, 0xb7, 0x4b, 0x1a, 0x53, 0x9e, 0xc0, 0xd8, 0x1a, 0x2b, 0xf5, 0xf5, 0xfd, 0x8d,
	0x2d, 0x37, 0xa6, 0xc9, 0x9f, 0x00, 0x4e, 0x6b, 0x5e, 0x33, 0x51, 0x5a, 0xd9, 0x9f, 0xcd, 0xe2,
	0x97, 0x30, 0x90, 0xd7, 0xec, 0xff, 0x45, 0xb1, 0x85, 0xb2, 0x57, 0x30, 0xac, 0x0a, 0xd9, 0xd9,
	0x7b, 0x9c, 0xd9, 0x05, 0x1f, 0x09, 0xea, 0x14, 0x4e, 0xc8, 0x4a, 0x5b, 0x91, 0xcb, 0x69, 0x20,
	0x9a, 0x2e, 0x19, 0xc3, 0xe8, 0x7d, 0xbe, 0xae, 0x8f, 0x76, 0xd1, 0x24, 0x29, 0x8c, 0xfd, 0xfd,
	0x02, 0x69, 0x6d, 0x0a, 0xc2, 0x0e, 0x33, 0xe8, 0x32, 0xe7, 0xbf, 0x7b, 0xde, 0xe8, 0x85, 0x37,
	0x91, 0xad, 0xe0, 0xfe, 0x3f, 0x81, 0x33, 0xbe, 0xdf, 0xef, 0x43, 0x7f, 0xc6, 0xe4, 0xec, 0x50,
	0x3e, 0xdb, 0x40, 0xbf, 0xc0, 0xe0, 0xdc, 0x98, 0x2b, 0xaf, 0x9f, 0x1c, 0xc5, 0x7b, 0xcd, 0xe9,
	0x61, 0xcc, 0x9e, 0xd8, 0x3e, 0xc1, 0x2d, 0x81, 0x84, 0xf6, 0x90, 0x74, 0xd7, 0xad, 0xc9, 0xe3,
	0xfd, 0x98, 0x5d, 0x07, 0xcf, 0xf9, 0xe7, 0x29, 0xa9, 0x7c, 0xad, 0xf1, 0x59, 0x89, 0x64, 0x57,
	0x95, 0x9e, 0xe1, 0x8f, 0x9c, 0xbe, 0xde, 0x78, 0x0b, 0x5e, 0xb7, 0x6f, 0xc1, 0xc5, 0x89, 0x13,
	0x7d, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xb6, 0xc5, 0x9b, 0x33, 0x04, 0x00, 0x00,
}
