version: "3.0"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_PORT=8080
        - APP_NAME=seat-api
        - APP_PATH=api/seat-api
    restart: always
    networks:
      - backend
    depends_on:
      - redis
    ports:
      - 8080:8080

  seat-svc:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_PORT=33033
        - APP_NAME=seat-svc
        - APP_PATH=grpc/seat-svc
        - CONFIG_PATH=conf/cinema.toml
    restart: always
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge